### ISSUE TITLE
wocky_db_watcher not restarting pod on DB connection failure

### ISSUE THREAD

**Issue by bernardd** [hippware/wocky_db_watcher#29]
@bernardd commented on [Sat Jan 05 2019](https://github.com/hippware/wocky/issues/2140)

It should either retry indefinitely or give up and die completely - turns out it doesn't do either.

---

@bernardd commented on [Tue Jan 08 2019](https://github.com/hippware/wocky/issues/2140#issuecomment-452145514)

I've tracked this down to what looks like an issue with Postgrex's notification system: https://github.com/elixir-ecto/postgrex/issues/433. I'll give it a few days to see what Jose et al have to say.

---

@bengtan commented on [Thu Jan 10 2019](https://github.com/hippware/wocky/issues/2140#issuecomment-452942603)

Is this related to PR #2147?

---

@bernardd commented on [Thu Jan 10 2019](https://github.com/hippware/wocky/issues/2140#issuecomment-452948993)

No

---

@bernardd commented on [Fri Feb 08 2019](https://github.com/hippware/wocky/issues/2140#issuecomment-461651657)

Got the go-ahead from the Postgrex maintainers to add a reconnection option, so I can work on this now.

---

@bengtan commented on [Fri Feb 08 2019](https://github.com/hippware/wocky/issues/2140#issuecomment-461677643)

Ack. Go ahead.

**Comment by toland** [comment]
I think we need to make a change to `wocky` so that the latest watcher will be deployed.

**Comment by bernardd** [comment]
Yep. I'll do that once #31 is merged.

**Comment by toland** [comment]
#31 is merged. 😄
